# This file is part of ZNC-Signal <https://github.com/poppyschmo/znc-signal>,
# licensed under Apache 2.0 <http://www.apache.org/licenses/LICENSE-2.0>.

"""
Miscellaneous objects for the DBus connection
"""
# XXX shocking/sad didn't grok static typing at all back whenever this file was
# last touched. Too scared to look. Too lazy to fix.

from jeepney.wrappers import MessageGenerator, new_method_call  # type: ignore[import]  # noqa: E501
from typing import List, Union
from collections import namedtuple


Incoming = namedtuple("Incoming",
                      "timestamp source groupID message attachments")


class SignalMG(MessageGenerator):
    """Modified auto-generated DBus bindings
    Generated by jeepney version 0.3.1
    Object path: /org/asamk/Signal
    Bus name   : org.asamk.Signal
    """
    interface = 'org.asamk.Signal'

    def __init__(self, object_path='/org/asamk/Signal',
                 bus_name='org.asamk.Signal'):
        super().__init__(object_path=object_path, bus_name=bus_name)

    def updateGroup(self, groupId: List[bytes], name: str, members: List[str],
                    avatar: str):
        return new_method_call(self, 'updateGroup', 'aysass',
                               (groupId, name, members, avatar))

    def sendEndSessionMessage(self, recipients: List[str]):
        return new_method_call(self, 'sendEndSessionMessage', 'as',
                               (recipients,))

    def sendGroupMessage(self, message: str, attachments: List[str],
                         groupId: List[bytes]):
        return new_method_call(self, 'sendGroupMessage', 'sasay',
                               (message, attachments, groupId))

    # Overloaded
    def sendMessage(
        self,
        message: str,
        attachments: List[str],
        recip: Union[str, List[str]]
    ):
        signature = "sass" if isinstance(recip, str) else "sasas"
        return new_method_call(self, 'sendMessage',
                               signature, (message, attachments, recip))

    def getContactName(self, number: str):
        return new_method_call(self, 'getContactName', 's', (number,))

    def setContactName(self, number: str, name: str):
        return new_method_call(self, 'setContactName', 'ss', (number, name))

    def getGroupName(self, groupId: List[bytes]):
        return new_method_call(self, 'getGroupName', 'ay', (groupId,))

    def getGroupMembers(self, groupId: List[bytes]):
        return new_method_call(self, 'getGroupMembers', 'ay', (groupId,))


signal_service = SignalMG()


def get_msggen(name):
    """Return a MessageGenerator instance for D-Bus object <name>"""
    if name == "Signal":
        mg = signal_service
    elif name == "DBus":
        from jeepney.bus_messages import message_bus  # type: ignore[import]
        mg = message_bus
    elif name in ("Stats", "Monitoring"):
        import jeepney.bus_messages as bm  # type: ignore[import]
        mg = getattr(bm, name)()
    else:
        raise ValueError("Unable to determine target object")
    return mg
